export const LANDING_PAGE = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const HOME = '/home'
export const ACCOUNT = '/account'
export const CREATE_NOTE = '/create-note'
export const NOTES = '/notes'
